Add missing include found by -Werror
stub-local/../stubdaemon.c:42:35: error:
      implicitly declaring library function 'strlen' with type 'unsigned long
      (const char *)' [-Werror]
                                  strlen(service_sockname)));
                                  ^
stub-local/../stubdaemon.c:42:35: note:
      include the header <string.h> or explicitly provide a declaration for 'strlen'
stub-local/../stubdaemon.c:165:23: error:
      implicit declaration of function 'strtok_r' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    for (char* line = strtok_r((output), "\n", &endptr);
                      ^
stub-local/../stubdaemon.c:165:16: error:
      incompatible integer to pointer conversion initializing 'char *' with an
      expression of type 'int' [-Werror,-Wint-conversion]
    for (char* line = strtok_r((output), "\n", &endptr);
               ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stub-local/../stubdaemon.c:167:15: error:
      incompatible integer to pointer conversion assigning to 'char *' from 'int'
      [-Werror,-Wint-conversion]
         line = strtok_r(NULL, "\n", &endptr))
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stub-local/../stubdaemon.c:383:9: error:
      implicitly declaring library function 'strcmp' with type 'int (const char *,
      const char *)' [-Werror]
    if (strcmp(dhello.ver, build_fingerprint) != 0) {
        ^
stub-local/../stubdaemon.c:383:9: note:
      include the header <string.h> or explicitly provide a declaration for 'strcmp'
stub-local/../stubdaemon.c:518:29: error:
      implicitly declaring library function 'strerror' with type 'char *(int)'
      [-Werror]
                            strerror(errno));
                            ^
stub-local/../stubdaemon.c:518:29: note:
      include the header <string.h> or explicitly provide a declaration for
      'strerror'
6 errors generated.