--enable-checking fails to bulid on non-Linux
stub-local/../stubdaemon.c:34:11: error:
      unused variable 'expected_uid' [-Werror,-Wunused-variable]
    uid_t expected_uid = xstat(xaprintf("/data/data/%s", package)).st_uid;
          ^
stub-local/../stubdaemon.c:90:28: error:
      implicit declaration of function 'get_peer_credentials' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    uid_t connection_uid = get_peer_credentials(connection).uid;
                           ^
stub-local/../stubdaemon.c:90:60: error:
      member reference base type 'int' is not a structure or union
    uid_t connection_uid = get_peer_credentials(connection).uid;
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~